<a href="https://colab.research.google.com/github/rgurjar8217git/my_python_git/blob/main/Copy_of_Module2_Activity2_1_NumPy_Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Course: Data Analytics Using Python (AIL0202)
## Module 2 – Activity 2.1
### NumPy Hands-on Lab (5 Marks)


### Instructions:
- Complete all tasks.
- Run each cell and show outputs.
- Add comments wherever required.
- Submit the completed notebook(PDF) on LMS.

Name: Rahul gurjar

Roll No.: BETN1AI25039


In [ ]:
# Import NumPy
import numpy as np
print('NumPy Version:', np.__version__)


## Task 1: Array Creation(1 Mark)

Create:

1D array of 10 integers

2D array (3×3 matrix)

Identity matrix of size 4

Random array (5×5)

In [ ]:
# Create required arrays here
import numpy as np

# 1D array of 10 integers
array_1d = np.arange(10)

# 3x3 matrix
matrix_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Identity matrix of size 4
identity_matrix = np.eye(4)
# Random 5x5 matrix
random_array = np.random.rand(5, 5)

print("1D Array:\n", array_1d)
print("\n3x3 Matrix:\n", matrix_2d)
print("\n4x4 Identity Matrix:\n", identity_matrix)
print("\n5x5 Random Array:\n", random_array)


1D Array:
 [0 1 2 3 4 5 6 7 8 9]

3x3 Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

4x4 Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

5x5 Random Array:
 [[0.81008359 0.75123877 0.51219438 0.02550779 0.66967576]
 [0.24291872 0.69070935 0.64445406 0.14258202 0.08341965]
 [0.52095673 0.01098963 0.48649773 0.47965405 0.49278375]
 [0.15882618 0.18655132 0.6264283  0.33813907 0.16647207]
 [0.4854684  0.37442884 0.80988713 0.31010927 0.18527951]]


## Task 2: Indexing & Slicing (1 Mark)

Given:

A = np.arange(1, 26).reshape(5,5)

Perform:

Extract 2nd row

Extract 3rd column

Extract 2×2 submatrix (center)

Reverse last row

In [ ]:
A = np.arange(1, 26).reshape(5,5)
print(A)

# Extract 2nd row
second_row = A[1, :]
print("\n 2nd Row:", second_row)
# Extract 3rd column
third_column = A[:, 2]
print("3rd Column:", third_column)
# Extract 2x2 center matrix
center_matrix = A[1:4, 1:4]
print("\n2x2 Center Matrix:\n", center_matrix)

# Reverse last row
reversed_last_row = A[-1, ::-1]
print("\nReversed Last Row:", reversed_last_row)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

2nd Row: [ 6  7  8  9 10]
3rd Column: [ 3  8 13 18 23]

2x2 Center Matrix:
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]

Reversed Last Row: [25 24 23 22 21]


## Task 3: Broadcasting(1 Mark)

Perform broadcasting operations on matrix A created in Task-2.

Add scalar 10 to matrix A

Add vector [1,2,3,4,5] to each row

Normalize matrix values between 0–1

In [ ]:
# Perform broadcasting operations here
import numpy as np
A = np.arange(1, 26).reshape(5,5)

# Add scalar 10 to matrix
A_plus_10 = A + 10
# Add vector [1,2,3,4,5] to each row
vector = np.array([1, 2, 3, 4, 5])
A_plus_vector = A + vector
# Normalize matrix between 0 and 1
A_min = A.min()
A_max = A.max()
A_normalized = (A - A_min) / (A_max - A_min)


print("1. Matrix A + 10:\n", A_plus_10)
print("\n2. Matrix A + Vector [1,2,3,4,5]:\n", A_plus_vector)
print("\n3. Normalized Matrix (0-1):\n", A_normalized)

1. Matrix A + 10:
 [[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]

2. Matrix A + Vector [1,2,3,4,5]:
 [[ 2  4  6  8 10]
 [ 7  9 11 13 15]
 [12 14 16 18 20]
 [17 19 21 23 25]
 [22 24 26 28 30]]

3. Normalized Matrix (0-1):
 [[0.         0.04166667 0.08333333 0.125      0.16666667]
 [0.20833333 0.25       0.29166667 0.33333333 0.375     ]
 [0.41666667 0.45833333 0.5        0.54166667 0.58333333]
 [0.625      0.66666667 0.70833333 0.75       0.79166667]
 [0.83333333 0.875      0.91666667 0.95833333 1.        ]]


## Task 4: Vectorized Computation(1 Marks)

Perform element-wise multiplication
Compute dot product
Compute mean, standard deviation

In [ ]:
X = np.array([1,2,3,4])
Y = np.array([5,6,7,8])

# Element-wise multiplication
element_wise = X * Y
# Dot product
dot_product = np.dot(X, Y)
# Mean and Standard Deviation
mean_x = np.mean(X)
std_dev_x = np.std(X)

print(f"Element-wise multiplication: {element_wise}")
print(f"Dot Product: {dot_product}")
print(f"Mean of X: {mean_x}")
print(f"Standard Deviation of X: {std_dev_x:.2f}")

Element-wise multiplication: [ 5 12 21 32]
Dot Product: 70
Mean of X: 2.5
Standard Deviation of X: 1.12


Task 5: Mini Case Problem (1 Mark)

Dataset: Student marks (5 students, 3 subjects)

Compute total and average per student

Find topper

Find subject-wise highest score

In [ ]:
marks = np.array([[80,75,90],[60,88,70],[95,92,85],[70,65,60],[88,78,84]])
# Compute totals, averages, topper
totals = marks.sum(axis=1)
averages = marks.mean(axis=1)

topper_index = np.argmax(totals)
topper_score = totals[topper_index]

subject_wise_highest = marks.max(axis=0)

print(f"Totals: {totals}")
print(f"Averages: {averages}")
print(f"Topper: Student {topper_index + 1} with {topper_score} marks")
print(f"Subject-wise Highest Scores: {subject_wise_highest}")


Totals: [245 218 272 195 250]
Averages: [81.66666667 72.66666667 90.66666667 65.         83.33333333]
Topper: Student 3 with 272 marks
Subject-wise Highest Scores: [95 92 90]
